# Generated by Django 4.2.4 on 2023-09-01 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_task_is_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
